server:
  port: 9000
  error:
    include-stacktrace: never
    include-message: never

firebase:
  projectId: prueba-396204
  credentialsPath: D:/clavesGCP/prueba-396204-fe0fcf9dc7f9.json

MercadoPago:
    property:
      authorization : "Bearer  APP_USR-146643112121987-011122-846e1f22a9a178a7c2ddcacasd14e56-99300811"
      url: "https://api.mercadopago.com/"

rutas:
  usuarios:
    saldos: prueba/web/com/usuarios/saldos

  reportes:
    transferencias: prueba/web/com/reportes/transferencias

spring:
  application:
    name: transferencias-bancarias

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317
  

# Configuración de Retries
resilience4j:
  retry:
    instances:
      myRetry:
        maxAttempts: 3
        waitDuration: 300ms
        retryExceptions: java.lang.Exception
        ignoreExceptions: java.lang.NullPointerException
        failAfterMaxAttempts: true
