server:
  port: 9000
  error:
    include-stacktrace: never
    include-message: never

firebase:
  projectId: prueba-396204
  credentialsPath: D:/clavesGCP/prueba-396204-fe0fcf9dc7f9.json

MercadoPago:
  Access-token: TEST-8677390478692229-122100-0d463c6230b4661fdac2fcbcadf56cd2-1586311014
  Public-Key: TEST-d6002a79-8a79-4227-94a2-c05debc1c525

rutas:
  usuarios:
    saldos: prueba/web/com/usuarios/saldos

  reportes:
    transferencias: prueba/web/com/reportes/transferencias

spring:
  application:
    name: transferencias-bancarias

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317
  

# Configuración de Retries
resilience4j:
  retry:
    instances:
      myRetry:
        maxAttempts: 3
        waitDuration: 300ms
        retryExceptions: java.lang.Exception
        ignoreExceptions: java.lang.NullPointerException
        failAfterMaxAttempts: true
